/**
 * Live wiring for the polish API routes (unit 2.3) — replaces the Phase 0
 * 503 stub.
 *
 * The request lifecycles live in lifecycle.ts / lifecycle-v2.ts
 * (dependency-injected, unit-tested); this module owns the production
 * dependencies and resolves them AT MODULE SCOPE when the deployment gate is
 * enabled, which is what gives the live routes their refuse-to-start semantics
 * (CP1 promise): importing this module throws — failing `next build` / `next
 * start` / the first request — instead of serving degraded requests, when the
 * enabled configuration is invalid:
 *
 * - POLISH_FAKE_LLM=true with NODE_ENV=production and no CI marker → throw
 * - real backend (POLISH_FAKE_BACKEND unset) without NEXT_PUBLIC_SUPABASE_URL
 *   / NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY / SUPABASE_SERVICE_ROLE_KEY /
 *   AI_USER_ID_HMAC_SECRET → throw
 * - POLISH_FAKE_BACKEND=true without POLISH_FAKE_LLM=true → throw
 * - POLISH_FAKE_LLM=true without POLISH_FAKE_BACKEND=true → throw for V2
 *
 * When AI_POLISH_ENABLED is anything other than the exact string `true`, the
 * module composes fixed 503 handlers without constructing auth, Supabase, or
 * provider dependencies. Provider credentials are profile-scoped and resolved only after DB reserve,
 * immutable execution snapshot and runtime-target attestation. A missing
 * selected credential therefore releases before attempt admission/network;
 * an unselected provider never becomes a startup dependency.
 *
 * Mode matrix:
 * - real backend: real provider + Supabase accounting. The legacy single
 *   POLISH_FAKE_LLM flag is rejected because synthetic inference cannot be
 *   represented under a real DB-frozen provider route.
 * - deterministic local/CI smoke: POLISH_FAKE_LLM=true plus
 *   POLISH_FAKE_BACKEND=true (+CI=true in a production process, set
 *   automatically by GitHub Actions) fakes the LLM and backend so `next
 *   start` serves the full lifecycle without Supabase.
 *
 * The raw Supabase user id never reaches the provider. V2 derives the
 * domain-separated provider subject only after the immutable execution
 * snapshot; the same server secret also keys separately domain-separated
 * opaque route-observation tags.
 *
 * Lives outside src/app so it always participates in typecheck; the route
 * files under src/app/api are generated by scripts/run-next-mode.mjs and
 * re-export POST / quota GET / availability GET from here.
 */

import type { PolishLogEvent, PolishQuotaRouteDeps } from "./lifecycle-types";
import {
  createPolishAvailabilityHandler,
  readPolishAvailabilityV1,
  type PolishAvailabilityDbResult,
  type PolishAvailabilityDeps,
  type PolishAvailabilityLogEvent,
} from "./lifecycle-availability";
import {
  bindPolishLifecycleV2,
  createPolishPostV2Handler,
  type PolishPostV2Deps,
  type PolishPostV2HttpLogEvent,
} from "./lifecycle-post-v2";
import type {
  PolishLifecycleV2LogEvent,
  PolishRouteDepsV2,
} from "./lifecycle-v2";
import { createRealPolishRuntimeAuthorityV2 } from "./handler-runtime-authority";
import { handleQuotaGet } from "./lifecycle-quota";
import { createPolishAuthDeps } from "./auth";
import { DEEPSEEK_POLISH_MODEL } from "./deepseek";
import {
  createFakePolishV2RouteDeps,
  FAKE_V2_EXPECTED_ROUTE,
  FAKE_V2_POLICY_VERSION_ID,
} from "./backend-fake";
import { resolveEndpoint } from "./adapter-registry";
import {
  createFakePolishInferenceProvider,
  createFakePolishProvider,
} from "./provider-fake";
import { assertFakeLlmDeploymentAllowed } from "./env";
import {
  isPolishDeploymentEnabled,
  type PolishHttpHandler,
  withPolishDeploymentGate,
} from "./deployment-gate";
import {
  completePolishProviderAttemptV2,
  finalizePolishRequestV2,
  getPolishExecutionSnapshotV1,
  getPolishQuota,
  recordPolishRequestCancellationV2,
  reservePolishRequestV2,
  startPolishProviderAttemptV2,
} from "./quota";
import { createServerAdminClient } from "@/server/supabase/admin-client";

const env = process.env;

function requireServerEnv(name: string): string {
  const value = env[name]?.trim();
  if (!value) {
    throw new Error(`Missing required server environment variable: ${name}`);
  }
  return value;
}

/** Structured metadata logger (no-store list enforced by PolishLogEvent). */
function logPolishEvent(event: PolishLogEvent): void {
  console.log(JSON.stringify(event));
}

function logPolishAvailabilityEvent(event: PolishAvailabilityLogEvent): void {
  console.log(JSON.stringify(event));
}

function logPolishLifecycleV2Event(event: PolishLifecycleV2LogEvent): void {
  console.log(JSON.stringify(event));
}

function logPolishPostV2Event(event: PolishPostV2HttpLogEvent): void {
  console.log(JSON.stringify(event));
}

interface PolishHandlerDeps {
  readonly quota: PolishQuotaRouteDeps;
  readonly availability: PolishAvailabilityDeps;
  readonly postV2: PolishPostV2Deps;
}

interface PolishHandlers {
  readonly POST: PolishHttpHandler;
  readonly GET: PolishHttpHandler;
  readonly AVAILABILITY_GET: PolishHttpHandler;
}

const FAKE_AVAILABILITY_ENABLED: PolishAvailabilityDbResult = Object.freeze({
  enabled: true,
  configGeneration: FAKE_V2_EXPECTED_ROUTE.configGeneration,
  routingPolicyVersionId: FAKE_V2_POLICY_VERSION_ID,
  profileVersionId: FAKE_V2_EXPECTED_ROUTE.profileVersionId,
  legalBundleVersion: FAKE_V2_EXPECTED_ROUTE.legalBundleVersion,
  runtimeContractId: FAKE_V2_EXPECTED_ROUTE.runtimeContractId,
  displayDisclosureKey: "deepseek-official-v1",
  termsAccepted: true,
});

function buildPolishHandlerDeps(): PolishHandlerDeps {
  // Apply the process-owned fake ceiling before constructing either backend.
  assertFakeLlmDeploymentAllowed(env);

  // CI smoke mode: fake auth/terms/quota behind an explicit second flag.
  if (env.POLISH_FAKE_BACKEND === "true") {
    if (env.POLISH_FAKE_LLM !== "true") {
      throw new Error(
        "POLISH_FAKE_BACKEND=true requires POLISH_FAKE_LLM=true: the fake backend exists " +
          "only for the CI smoke alongside the deterministic fake LLM. Refusing to start.",
      );
    }
    const provider = createFakePolishProvider();
    const providerV2 = createFakePolishInferenceProvider({
      route: {
        actualUpstreamEndpoint: resolveEndpoint("deepseek_official").url,
        actualModelId: DEEPSEEK_POLISH_MODEL,
      },
    });
    const fakeV2 = createFakePolishV2RouteDeps({ provider, providerV2, env });
    const quota: PolishQuotaRouteDeps = {
      verifyAccessToken: fakeV2.legacyV1.verifyAccessToken,
      getQuota: fakeV2.legacyV1.getQuota,
      aiPolishEnabled: true,
      logger: logPolishEvent,
    };
    return {
      quota,
      availability: {
        verifyAccessToken: fakeV2.legacyV1.verifyAccessToken,
        readAvailability: async () => FAKE_AVAILABILITY_ENABLED,
        logger: logPolishAvailabilityEvent,
      },
      postV2: {
        verifyAccessToken: fakeV2.legacyV1.verifyAccessToken,
        executeLifecycle: bindPolishLifecycleV2({
          ...fakeV2,
          logger: logPolishLifecycleV2Event,
        }),
        logger: logPolishPostV2Event,
      },
    };
  }

  // Real backend: auth/accounting against Supabase. The authority factory
  // rejects the unsupported single fake-LLM flag and structurally pins this
  // branch to reviewed DeepSeek runtime attestation plus code-owned adapters.
  const runtimeAuthority = createRealPolishRuntimeAuthorityV2(env);
  const authDeps = createPolishAuthDeps();
  const adminClient = createServerAdminClient();
  // All provider subjects/route tags are server-keyed so raw identity or
  // correlation values cannot cross boundaries.
  const hmacSecret = requireServerEnv("AI_USER_ID_HMAC_SECRET");
  const routesV2: PolishRouteDepsV2 = {
    reserve: (params) => reservePolishRequestV2(adminClient, params),
    getExecutionSnapshot: (params) => getPolishExecutionSnapshotV1(adminClient, params),
    startAttempt: (params) => startPolishProviderAttemptV2(adminClient, params),
    completeAttempt: (params) => completePolishProviderAttemptV2(adminClient, params),
    recordCancellation: (params) =>
      recordPolishRequestCancellationV2(adminClient, params),
    finalize: (params, options) =>
      finalizePolishRequestV2(adminClient, params, options),
    ...runtimeAuthority,
    providerSubjectSecret: hmacSecret,
    routeObservationSecret: hmacSecret,
    logger: logPolishLifecycleV2Event,
  };

  return {
    quota: {
      verifyAccessToken: authDeps.verifyAccessToken,
      getQuota: (userId) => getPolishQuota(adminClient, userId),
      // The shared deployment gate owns this ceiling. Reaching the real quota
      // handler proves the module-scope value was the exact string `true`.
      aiPolishEnabled: true,
      logger: logPolishEvent,
    },
    availability: {
      verifyAccessToken: authDeps.verifyAccessToken,
      readAvailability: (userId) => readPolishAvailabilityV1(adminClient, userId),
      logger: logPolishAvailabilityEvent,
    },
    postV2: {
      verifyAccessToken: authDeps.verifyAccessToken,
      executeLifecycle: bindPolishLifecycleV2(routesV2),
      logger: logPolishPostV2Event,
    },
  };
}

function composePolishHandlers(): PolishHandlers {
  const deploymentAiEnabled = isPolishDeploymentEnabled(env.AI_POLISH_ENABLED);
  if (!deploymentAiEnabled) {
    const unreachable: PolishHttpHandler = async () => {
      throw new Error("disabled polish deployment delegated downstream");
    };
    const disabled = withPolishDeploymentGate(false, unreachable);
    return {
      POST: disabled,
      GET: disabled,
      AVAILABILITY_GET: disabled,
    };
  }

  // Module-scope resolution is the enabled deployment's refuse-to-start
  // mechanism: any live-backend misconfiguration throws before serving.
  const deps = buildPolishHandlerDeps();
  return {
    POST: withPolishDeploymentGate(true, createPolishPostV2Handler(deps.postV2)),
    GET: withPolishDeploymentGate(true, (request: Request) =>
      handleQuotaGet(request, deps.quota),
    ),
    AVAILABILITY_GET: withPolishDeploymentGate(
      true,
      createPolishAvailabilityHandler(deps.availability),
    ),
  };
}

const handlers = composePolishHandlers();

export const POST = handlers.POST;
export const GET = handlers.GET;
export const AVAILABILITY_GET = handlers.AVAILABILITY_GET;
