/**
 * Live wiring for the polish API routes (unit 2.3) — replaces the Phase 0
 * 503 stub.
 *
 * The request lifecycle itself lives in lifecycle.ts (dependency-injected,
 * unit-tested); this module owns the PRODUCTION dependencies and resolves
 * them AT MODULE SCOPE, which is what gives the routes their refuse-to-start
 * semantics (CP1 promise): importing this module throws — failing `next
 * build` / `next start` / the first request — instead of serving degraded
 * requests, when the configuration is invalid:
 *
 * - real provider (POLISH_FAKE_LLM unset) without DEEPSEEK_API_KEY → throw
 * - POLISH_FAKE_LLM=true with NODE_ENV=production and no CI marker → throw
 * - real backend (POLISH_FAKE_BACKEND unset) without NEXT_PUBLIC_SUPABASE_URL
 *   / NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY / SUPABASE_SERVICE_ROLE_KEY /
 *   AI_USER_ID_HMAC_SECRET → throw
 * - POLISH_FAKE_BACKEND=true without POLISH_FAKE_LLM=true → throw
 *
 * Mode matrix:
 * - production: real provider + real Supabase backend.
 * - local dev: POLISH_FAKE_LLM=true fakes ONLY the LLM; auth/terms/quota
 *   still run against the local Supabase (the manual full-chain verification
 *   path).
 * - CI smoke: POLISH_FAKE_LLM=true + POLISH_FAKE_BACKEND=true (+CI=true
 *   marker, set automatically by GitHub Actions) fakes the LLM and the
 *   backend so `next start` serves the full lifecycle without Supabase.
 *
 * The raw supabase user id never reaches the provider: the handler derives
 * providerUserId = HMAC_SHA256(AI_USER_ID_HMAC_SECRET, userId) as hex
 * (roadmap「发给 DeepSeek 的 user 标识」) and the provider forwards it
 * unchanged.
 *
 * Lives outside src/app so it always participates in typecheck; the route
 * files under src/app/api are generated by scripts/run-next-mode.mjs and
 * re-export POST / quota GET / availability GET from here.
 */

import { createHmac } from "node:crypto";

import { createPolishHandlers, type PolishLogEvent, type PolishRouteDeps } from "./lifecycle";
import {
  createPolishAvailabilityHandler,
  readPolishAvailabilityV1,
  type PolishAvailabilityDbResult,
  type PolishAvailabilityDeps,
  type PolishAvailabilityLogEvent,
} from "./lifecycle-availability";
import { getPolishProvider } from "./provider";
import { createPolishAuthDeps } from "./auth";
import { DEEPSEEK_POLISH_MODEL } from "./deepseek";
import { createFakePolishRouteDeps } from "./backend-fake";
import {
  finalizePolishRequest,
  getPolishQuota,
  markPolishProviderStarted,
  reservePolishRequest,
} from "./quota";
import { createServerAdminClient } from "@/server/supabase/admin-client";

const env = process.env;

function requireServerEnv(name: string): string {
  const value = env[name]?.trim();
  if (!value) {
    throw new Error(`Missing required server environment variable: ${name}`);
  }
  return value;
}

/** Structured metadata logger (no-store list enforced by PolishLogEvent). */
function logPolishEvent(event: PolishLogEvent): void {
  console.log(JSON.stringify(event));
}

function logPolishAvailabilityEvent(event: PolishAvailabilityLogEvent): void {
  console.log(JSON.stringify(event));
}

interface PolishHandlerDeps {
  readonly routes: PolishRouteDeps;
  readonly availability: PolishAvailabilityDeps;
}

const FAKE_AVAILABILITY_DISABLED: PolishAvailabilityDbResult = Object.freeze({
  enabled: false,
  configGeneration: null,
  routingPolicyVersionId: null,
  profileVersionId: null,
  legalBundleVersion: null,
  runtimeContractId: null,
  runtimeContractSha256: null,
  displayDisclosureKey: null,
  termsAccepted: false,
});

const FAKE_AVAILABILITY_ENABLED: PolishAvailabilityDbResult = Object.freeze({
  enabled: true,
  configGeneration: "0",
  routingPolicyVersionId: "00000000-0000-4000-8000-0000000000a1",
  profileVersionId: "00000000-0000-4000-8000-0000000000a2",
  legalBundleVersion: "2026-08-23-multi-provider-v1",
  runtimeContractId: "fake-deepseek-runtime-v1",
  runtimeContractSha256: "0".repeat(64),
  displayDisclosureKey: "deepseek-official-v1",
  termsAccepted: true,
});

function buildPolishHandlerDeps(): PolishHandlerDeps {
  // Provider resolution applies the fake-in-production guard in every mode.
  const provider = getPolishProvider(env);

  // CI smoke mode: fake auth/terms/quota behind an explicit second flag.
  if (env.POLISH_FAKE_BACKEND === "true") {
    if (env.POLISH_FAKE_LLM !== "true") {
      throw new Error(
        "POLISH_FAKE_BACKEND=true requires POLISH_FAKE_LLM=true: the fake backend exists " +
          "only for the CI smoke alongside the deterministic fake LLM. Refusing to start.",
      );
    }
    const routes: PolishRouteDeps = {
      ...createFakePolishRouteDeps({ provider, env }),
      logger: logPolishEvent,
    };
    return {
      routes,
      availability: {
        verifyAccessToken: routes.verifyAccessToken,
        readAvailability: async () =>
          env.AI_POLISH_ENABLED === "true"
            ? FAKE_AVAILABILITY_ENABLED
            : FAKE_AVAILABILITY_DISABLED,
        logger: logPolishAvailabilityEvent,
      },
    };
  }

  // Real backend: auth/terms/quota against Supabase. Both factories throw on
  // missing env (refuse-to-start).
  const authDeps = createPolishAuthDeps();
  const adminClient = createServerAdminClient();
  // Required even with the fake LLM: providerUserId is always HMAC-derived so
  // the raw supabase user id can never leak into a provider request.
  const hmacSecret = requireServerEnv("AI_USER_ID_HMAC_SECRET");

  return {
    routes: {
      verifyAccessToken: authDeps.verifyAccessToken,
      hasAcceptedCurrentAiTerms: authDeps.hasAcceptedCurrentAiTerms,
      reserve: (params) => reservePolishRequest(adminClient, params),
      markProviderStarted: (reservationId, providerRequestId) =>
        markPolishProviderStarted(adminClient, reservationId, providerRequestId),
      finalize: (params) => finalizePolishRequest(adminClient, params),
      getQuota: (userId) => getPolishQuota(adminClient, userId),
      provider,
      providerUserId: (userId) =>
        createHmac("sha256", hmacSecret).update(userId).digest("hex"),
      model: DEEPSEEK_POLISH_MODEL,
      aiPolishEnabled: env.AI_POLISH_ENABLED === "true",
      logger: logPolishEvent,
    },
    availability: {
      verifyAccessToken: authDeps.verifyAccessToken,
      readAvailability: (userId) => readPolishAvailabilityV1(adminClient, userId),
      logger: logPolishAvailabilityEvent,
    },
  };
}

// Module-scope resolution IS the refuse-to-start mechanism: any
// misconfiguration above throws during import, before a request is served.
const deps = buildPolishHandlerDeps();
const handlers = createPolishHandlers(deps.routes);

export const POST = handlers.POST;
export const GET = handlers.GET;
export const AVAILABILITY_GET = createPolishAvailabilityHandler(deps.availability);
