/**
 * Phase 0 stub for the polish API routes (unit 0.1).
 *
 * The real request lifecycle (auth → terms → bounded reader → dedup →
 * reserve → orchestrator → finalize) lands in unit 2.3. Until then both
 * routes respond 503 AI_DISABLED so that the dual-mode build and CI smoke
 * have a requestable endpoint; CI asserts 503 (2.3 updates it to 401 for
 * token-less requests).
 *
 * Lives outside src/app so it always participates in typecheck; the route
 * files under src/app/api are generated by scripts/run-next-mode.mjs.
 */

import { randomUUID } from "node:crypto";
import { POLISH_ERROR_HTTP_STATUS, type PolishErrorResponse } from "@/lib/polish/contract";

function aiDisabled(): Response {
  const body: PolishErrorResponse = {
    requestId: randomUUID(),
    error: {
      code: "AI_DISABLED",
      message: "AI polish is not available (Phase 0 stub).",
    },
  };
  return Response.json(body, {
    status: POLISH_ERROR_HTTP_STATUS.AI_DISABLED,
    headers: {
      "Cache-Control": "no-store",
      "X-Request-Id": body.requestId,
    },
  });
}

export function POST(): Response {
  return aiDisabled();
}

export function GET(): Response {
  return aiDisabled();
}
