import { describe, expect, it } from "vitest";
import {
  fingerprintLegalDescriptorV1,
  LEGAL_FINGERPRINT_MAX_ARRAY_ITEMS,
  LegalFingerprintV1Error,
} from "./legal-fingerprint-v1";

const ASCII_ROUTE = Object.freeze({
  schema_version: "ai_legal_route_identity_v1",
  route_descriptor_id: "route.deepseek.v1",
  profile_key: "deepseek.official.deepseek-v4-flash.chat.v1",
  gateway_kind: "direct_deepseek",
  operator_identity_status: "known",
  operator_legal_name: "Hangzhou DeepSeek Artificial Intelligence Co., Ltd.",
  model_vendor_id: "deepseek",
  model_vendor_name: "DeepSeek",
  model_id: "deepseek-v4-flash",
  wire_api_kind: "chat_completions_v1",
  endpoint_alias: "deepseek_official",
  canonical_endpoint_url: "https://api.deepseek.com/chat/completions",
  display_disclosure_key: "deepseek-official-v1",
});

// Generated by an independent PowerShell/.NET UTF-8 record builder and SHA256,
// not by fingerprintLegalDescriptorV1 or any production helper.
const ASCII_ROUTE_STREAM_HEX =
  "61695f66696e6765727072696e745f7265636f72645f76310a31343a736368656d615f76657273696f6e3a32363a61695f6c6567616c5f726f7574655f6964656e746974795f76310a31393a726f7574655f64657363726970746f725f69643a31373a726f7574652e646565707365656b2e76310a31313a70726f66696c655f6b65793a34333a646565707365656b2e6f6666696369616c2e646565707365656b2d76342d666c6173682e636861742e76310a31323a676174657761795f6b696e643a31353a6469726563745f646565707365656b0a32343a6f70657261746f725f6964656e746974795f7374617475733a353a6b6e6f776e0a31393a6f70657261746f725f6c6567616c5f6e616d653a35313a48616e677a686f7520446565705365656b204172746966696369616c20496e74656c6c6967656e636520436f2e2c204c74642e0a31353a6d6f64656c5f76656e646f725f69643a383a646565707365656b0a31373a6d6f64656c5f76656e646f725f6e616d653a383a446565705365656b0a383a6d6f64656c5f69643a31373a646565707365656b2d76342d666c6173680a31333a776972655f6170695f6b696e643a31393a636861745f636f6d706c6574696f6e735f76310a31343a656e64706f696e745f616c6961733a31373a646565707365656b5f6f6666696369616c0a32323a63616e6f6e6963616c5f656e64706f696e745f75726c3a34313a68747470733a2f2f6170692e646565707365656b2e636f6d2f636861742f636f6d706c6574696f6e730a32323a646973706c61795f646973636c6f737572655f6b65793a32303a646565707365656b2d6f6666696369616c2d76310a";
const ASCII_ROUTE_SHA256 = "cd9f9a0448d48443fb591d89254743c7e6cbfa3a9fc54a2ccc700efe7a8742c7";

const MULTIBYTE_FACT = Object.freeze({
  schema_version: "ai_legal_fact_v1",
  fact_id: "fact.multibyte.v1",
  category: "display",
  authority_class: "service-display",
  operational_scope: "",
  status: "confirmed",
  subject: "AI 条款",
  predicate: "uses reviewed label",
  object: "Café / 数据🔐",
  scope: "locale-neutral semantic meaning",
  qualifiers: ["中文", "Café"],
});

const MULTIBYTE_FACT_STREAM_HEX =
  "61695f66696e6765727072696e745f7265636f72645f76310a31343a736368656d615f76657273696f6e3a31363a61695f6c6567616c5f666163745f76310a373a666163745f69643a31373a666163742e6d756c7469627974652e76310a383a63617465676f72793a373a646973706c61790a31353a617574686f726974795f636c6173733a31353a736572766963652d646973706c61790a31373a6f7065726174696f6e616c5f73636f70653a303a0a363a7374617475733a393a636f6e6669726d65640a373a7375626a6563743a393a414920e69da1e6acbe0a393a7072656469636174653a31393a75736573207265766965776564206c6162656c0a363a6f626a6563743a31383a436166c3a9202f20e695b0e68daef09f94900a353a73636f70653a33313a6c6f63616c652d6e65757472616c2073656d616e746963206d65616e696e670a31363a7175616c6966696572732e636f756e743a313a320a31323a7175616c6966696572732e303a353a436166c3a90a31323a7175616c6966696572732e313a363ae4b8ade696870a";
const MULTIBYTE_FACT_SHA256 = "297b52ff74ec77a049e1e4864f980f65fff636749287bb45e155cb9f5db79e47";

describe("legal fingerprint v1 canonicalizer", () => {
  it("matches the independent ASCII exact-byte and SHA-256 vector", () => {
    const result = fingerprintLegalDescriptorV1(ASCII_ROUTE);
    expect(result.bytes.toString("hex")).toBe(ASCII_ROUTE_STREAM_HEX);
    expect(result.sha256).toBe(ASCII_ROUTE_SHA256);
  });

  it("normalizes NFC, sorts a set by UTF-8 bytes, and matches the independent multibyte vector", () => {
    const result = fingerprintLegalDescriptorV1({
      ...MULTIBYTE_FACT,
      object: "Cafe\u0301 / 数据🔐",
      qualifiers: ["中文", "Cafe\u0301"],
    });
    expect(result.normalized.object).toBe("Café / 数据🔐");
    expect(result.normalized.qualifiers).toEqual(["Café", "中文"]);
    expect(result.bytes.toString("hex")).toBe(MULTIBYTE_FACT_STREAM_HEX);
    expect(result.sha256).toBe(MULTIBYTE_FACT_SHA256);
  });

  it.each(["\ud800", "\udc00", "text\ud800more"])(
    "rejects a lone surrogate before UTF-8 encoding (%j)",
    (object) => {
      expect(() => fingerprintLegalDescriptorV1({ ...MULTIBYTE_FACT, object })).toThrow(
        /lone UTF-16 surrogate/,
      );
    },
  );

  it("rejects NFC-equivalent duplicate set elements instead of silently deduplicating", () => {
    expect(() =>
      fingerprintLegalDescriptorV1({
        ...MULTIBYTE_FACT,
        qualifiers: ["Café", "Cafe\u0301"],
      }),
    ).toThrow(/NFC-duplicate/);
  });

  it("sorts ID/hash pairs together and rejects duplicate IDs", () => {
    const hashA = "a".repeat(64);
    const hashB = "b".repeat(64);
    const manifest = {
      schema_version: "ai_legal_manifest_fingerprint_v1",
      manifest_id: "manifest.v1",
      display_disclosure_key: "display.v1",
      reviewed_at: "2026-08-23@Asia/Shanghai",
      route_descriptor_ids: ["route.z", "route.a"],
      route_descriptor_sha256s: [hashB, hashA],
      subject_descriptor_id: "subject.v1",
      subject_descriptor_sha256: hashA,
      fact_ids: ["fact.z", "fact.a"],
      fact_sha256s: [hashB, hashA],
      evidence_ids: ["evidence.z", "evidence.a"],
      evidence_sha256s: [hashB, hashA],
    };
    const normalized = fingerprintLegalDescriptorV1(manifest).normalized;
    expect(normalized.route_descriptor_ids).toEqual(["route.a", "route.z"]);
    expect(normalized.route_descriptor_sha256s).toEqual([hashA, hashB]);
    expect(() =>
      fingerprintLegalDescriptorV1({
        ...manifest,
        fact_ids: ["fact.a", "fact.a"],
      }),
    ).toThrow(/equal length|duplicate pair ID/);
  });

  it.each([
    ["missing", Object.fromEntries(Object.entries(ASCII_ROUTE).filter(([key]) => key !== "model_id"))],
    ["unknown", { ...ASCII_ROUTE, surprise: "x" }],
    ["wrong scalar type", { ...ASCII_ROUTE, model_id: 42 }],
    ["wrong boolean type", {
      schema_version: "ai_legal_provider_subject_v1",
      subject_descriptor_id: "subject.none.v1",
      mode: "none",
      wire_field: "",
      algorithm: "",
      secret_class: "",
      derivation_message_schema: "",
      output_encoding: "",
      source_identity_class: "",
      raw_email_sent: "false",
      raw_username_sent: false,
      raw_account_id_sent: false,
      documented_purposes: [],
    }],
  ])("rejects a descriptor with %s fields", (_label, descriptor) => {
    expect(() => fingerprintLegalDescriptorV1(descriptor)).toThrow(LegalFingerprintV1Error);
  });

  it("enforces enum, conditional-empty, code-ID, SHA and date grammars", () => {
    expect(() => fingerprintLegalDescriptorV1({ ...ASCII_ROUTE, operator_identity_status: "maybe" })).toThrow(/enum/);
    expect(() => fingerprintLegalDescriptorV1({ ...ASCII_ROUTE, operator_identity_status: "unverified" })).toThrow(/operator_legal_name/);
    expect(() => fingerprintLegalDescriptorV1({ ...ASCII_ROUTE, route_descriptor_id: "é" })).toThrow(/ASCII code ID/);
    expect(() => fingerprintLegalDescriptorV1({
      schema_version: "ai_legal_manifest_fingerprint_v1",
      manifest_id: "manifest.v1", display_disclosure_key: "display.v1",
      reviewed_at: "2026-08-23T00:00:00Z",
      route_descriptor_ids: ["route.v1"], route_descriptor_sha256s: ["a".repeat(64)],
      subject_descriptor_id: "subject.v1", subject_descriptor_sha256: "a".repeat(64),
      fact_ids: ["fact.v1"], fact_sha256s: ["a".repeat(64)],
      evidence_ids: ["evidence.v1"], evidence_sha256s: ["a".repeat(64)],
    })).toThrow(/reviewed_at/);
  });

  it("rejects oversized arrays before record construction", () => {
    expect(() => fingerprintLegalDescriptorV1({
      ...MULTIBYTE_FACT,
      qualifiers: Array.from({ length: LEGAL_FINGERPRINT_MAX_ARRAY_ITEMS + 1 }, (_, index) => `q${index}`),
    })).toThrow(/item limit/);
  });

  it("rejects sparse arrays, array extra properties, and symbol-keyed descriptor fields", () => {
    const sparse = new Array<string>(1);
    expect(() => fingerprintLegalDescriptorV1({ ...MULTIBYTE_FACT, qualifiers: sparse })).toThrow(/sparse/);
    const extra = ["reviewed"];
    Object.defineProperty(extra, "extra", { value: "hidden", enumerable: true });
    expect(() => fingerprintLegalDescriptorV1({ ...MULTIBYTE_FACT, qualifiers: extra })).toThrow(/extra properties/);
    const symbol = Symbol("unknown");
    expect(() => fingerprintLegalDescriptorV1({ ...ASCII_ROUTE, [symbol]: "x" })).toThrow(/symbol/);
  });
});
